import type { ResidenceSlug, ResidenceStatus } from "./content-types";

export type ResidenceBase = {
  slug: ResidenceSlug;
  name: string;
  neighborhood: string;
  status: ResidenceStatus;
  area: string;
  image: string;
  gallery: readonly string[];
};

export const residenceBase: readonly ResidenceBase[] = [
  { slug: "brise", name: "Brise by Conviva", neighborhood: "Camboinhas", status: "current", area: "37,94-94,99 m²", image: "/images/residences/brise-1.webp", gallery: ["/images/residences/brise-1.webp", "/images/residences/brise-2.webp", "/images/residences/brise-3.webp", "/images/residences/brise-4.webp", "/images/residences/brise-5.webp", "/images/residences/brise-6.webp", "/images/residences/brise-7.webp", "/images/residences/brise-8.webp"] },
  { slug: "life-inga", name: "Life Ingá", neighborhood: "Ingá", status: "current", area: "32,58-67,33 m²", image: "/images/residences/life-inga-1.webp", gallery: ["/images/residences/life-inga-1.webp", "/images/residences/life-inga-2.webp", "/images/residences/life-inga-3.webp", "/images/residences/life-inga-4.webp", "/images/residences/life-inga-5.webp", "/images/residences/life-inga-6.webp", "/images/residences/life-inga-7.webp", "/images/residences/life-inga-8.webp"] },
  { slug: "life-camboinhas", name: "Life Camboinhas", neighborhood: "Camboinhas", status: "current", area: "37,43-123,66 m²", image: "/images/life-camboinhas-fachada-nova.jpg", gallery: ["/images/residences/life-camboinhas-1.webp", "/images/residences/life-camboinhas-2.webp", "/images/residences/life-camboinhas-3.webp", "/images/residences/life-camboinhas-4.webp", "/images/residences/life-camboinhas-5.webp", "/images/residences/life-camboinhas-6.webp", "/images/residences/life-camboinhas-7.webp", "/images/residences/life-camboinhas-8.webp"] },
  { slug: "conviva-camboinhas", name: "Conviva Camboinhas", neighborhood: "Camboinhas", status: "current", area: "41-109 m²", image: "/images/residences/conviva-camboinhas-1.webp", gallery: ["/images/residences/conviva-camboinhas-1.webp", "/images/residences/conviva-camboinhas-2.webp", "/images/residences/conviva-camboinhas-3.webp", "/images/residences/conviva-camboinhas-4.webp", "/images/residences/conviva-camboinhas-5.webp", "/images/residences/conviva-camboinhas-6.webp", "/images/residences/conviva-camboinhas-7.webp", "/images/residences/conviva-camboinhas-8.webp"] },
  { slug: "conviva-icarai", name: "Conviva Icaraí", neighborhood: "Icaraí", status: "current", area: "31,70-83,65 m²", image: "/images/residences/conviva-icarai-1.webp", gallery: ["/images/residences/conviva-icarai-1.webp", "/images/residences/conviva-icarai-2.webp", "/images/residences/conviva-icarai-3.webp", "/images/residences/conviva-icarai-4.webp", "/images/residences/conviva-icarai-5.webp", "/images/residences/conviva-icarai-6.webp", "/images/residences/conviva-icarai-7.webp", "/images/residences/conviva-icarai-8.webp"] },
  { slug: "conviva-itacoa", name: "Conviva Itacoa", neighborhood: "Itaipu", status: "current", area: "39,03-62,33 m²", image: "/images/residences/conviva-itacoa-1.webp", gallery: ["/images/residences/conviva-itacoa-1.webp", "/images/residences/conviva-itacoa-2.webp", "/images/residences/conviva-itacoa-3.webp", "/images/residences/conviva-itacoa-4.webp", "/images/residences/conviva-itacoa-5.webp", "/images/residences/conviva-itacoa-6.webp", "/images/residences/conviva-itacoa-7.webp", "/images/residences/conviva-itacoa-8.webp"] },
  { slug: "nice-camboinhas", name: "Nice Camboinhas", neighborhood: "Camboinhas", status: "current", area: "66,25-327,84 m²", image: "/images/residences/nice-camboinhas-1.webp", gallery: ["/images/residences/nice-camboinhas-1.webp", "/images/residences/nice-camboinhas-2.webp", "/images/residences/nice-camboinhas-3.webp", "/images/residences/nice-camboinhas-4.webp", "/images/residences/nice-camboinhas-5.webp", "/images/residences/nice-camboinhas-6.webp", "/images/residences/nice-camboinhas-7.webp", "/images/residences/nice-camboinhas-8.webp"] },
  { slug: "conviva-piratininga", name: "Conviva Piratininga", neighborhood: "Piratininga", status: "completed", area: "36,11-88,55 m²", image: "/images/residences/conviva-piratininga-1.webp", gallery: ["/images/residences/conviva-piratininga-1.webp", "/images/residences/conviva-piratininga-2.webp", "/images/residences/conviva-piratininga-3.webp", "/images/residences/conviva-piratininga-4.webp", "/images/residences/conviva-piratininga-5.webp", "/images/residences/conviva-piratininga-6.webp", "/images/residences/conviva-piratininga-7.webp", "/images/residences/conviva-piratininga-8.webp"] },
  { slug: "conviva-inga", name: "Conviva Ingá", neighborhood: "Ingá", status: "completed", area: "32,57-101,65 m²", image: "/images/residences/conviva-inga-1.webp", gallery: ["/images/residences/conviva-inga-1.webp", "/images/residences/conviva-inga-2.webp", "/images/residences/conviva-inga-3.webp", "/images/residences/conviva-inga-4.webp", "/images/residences/conviva-inga-5.webp", "/images/residences/conviva-inga-6.webp", "/images/residences/conviva-inga-7.webp", "/images/residences/conviva-inga-8.webp"] },
];
